display:
  display-name: "Slayer"
  lore:
    - "&7Kill %required% skeletons"
    - "&7%current%/%required%"

xp-gain-methods:
  - trigger: kill
    value: 1
    filters:
      entities:
        - SKELETON
