display:
  display-name: "Miner"
  lore:
    - "&7Mine %required% ancient debris"
    - "&7%current%/%required%"

xp-gain-methods:
  - trigger: mine_block
    multiplier: 1
    filters:
      blocks:
        - "ANCIENT_DEBRIS"
      player_placed: false