display:
  display-name: "Miner"
  lore:
    - "&7Mine %required% copper ore"
    - "&7%current%/%required%"

xp-gain-methods:
  - trigger: mine_block
    multiplier: 1
    filters:
      blocks:
        - "COPPER_ORE"
        - "DEEPSLATE_COPPER_ORE"
      player_placed: false