display:
  display-name: "Miner"
  lore:
    - "&7Mine %required% quartz ore"
    - "&7%current%/%required%"

xp-gain-methods:
  - trigger: mine_block
    multiplier: 1
    filters:
      blocks:
        - "NETHER_QUARTZ_ORE"
      player_placed: false