display:
  display-name: "Miner"
  lore:
    - "&7Mine %required% emerald ore"
    - "&7%current%/%required%"

xp-gain-methods:
  - trigger: mine_block
    multiplier: 1
    filters:
      blocks:
        - "EMERALD_ORE"
        - "DEEPSLATE_EMERALD_ORE"
      player_placed: false