display:
  display-name: Miner
  lore:
    - "&7Mine %required% coal ore"
    - "&7%current%/%required%"

xp-gain-methods:
  - trigger: mine_block
    multiplier: 1
    filters:
      blocks:
        - "COAL_ORE"
        - "DEEPSLATE_COAL_ORE"
      player_placed: false