display:
  display-name: "We Must Go Deeper"
  lore:
    - "&7Visit the Nether"
    - "&7%current%/%required%"

xp-gain-methods:
  - trigger: change_world
    value: 1
    conditions:
      - id: in_world
        args:
          world: world_nether